version: '3'

services:
  proxy:
    image: traefik:v1.6.6-alpine
    command: --web --docker --logLevel=INFO
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:traefik.cloudgang.online"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=username:htpasswdhashstring"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
networks:
  web:
    external: true
