version: '3'
services:
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mariadb.cloudgang.online"
      - "traefik.port=3306"
      - "traefik.docker.network=web"
    networks:
      - web
      - default

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8585:8585"
    networks:
      - nextcloud_network
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nextcloud.cloudgang.online"
      - "traefik.frontend.auth.forward.tls.insecureSkipVerify=true"
      - "traefik.protocol=http"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - default

volumes:
  nextcloud:
  db:

networks:
  default:
    external:
      name: nextcloud
  web:
    external: true # For traefik
